# Generated by Django 5.1.7 on 2025-04-11 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='documents/original/%Y/%m/%d/', verbose_name='Documento Original')),
                ('original_filename', models.CharField(editable=False, max_length=255)),
                ('watermark_image', models.ImageField(upload_to='watermarks/%Y/%m/%d/', verbose_name="Imagem de Marca D'Água")),
                ('watermark_opacity', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.9)], verbose_name="Transparência da Marca D'Água")),
                ('watermark_position', models.CharField(choices=[('center', 'Centro'), ('topleft', 'Canto Superior Esquerdo'), ('topright', 'Canto Superior Direito'), ('bottomleft', 'Canto Inferior Esquerdo'), ('bottomright', 'Canto Inferior Direito')], default='center', max_length=20, verbose_name="Posição da Marca D'Água")),
                ('signature_text', models.CharField(max_length=255, verbose_name='Texto da Assinatura')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/%d/', verbose_name='Imagem da Assinatura')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='documents/signed/%Y/%m/%d/', verbose_name='Documento Assinado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Documento Assinado',
                'verbose_name_plural': 'Documentos Assinados',
                'ordering': ['-created_at'],
            },
        ),
    ]
