# Generated by Django 5.0.3 on 2025-04-16 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signeddocument',
            options={},
        ),
        migrations.RemoveField(
            model_name='signeddocument',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='signeddocument',
            name='status',
        ),
        migrations.RemoveField(
            model_name='signeddocument',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='signeddocument',
            name='signature_position',
            field=models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='left', max_length=10),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='original_file',
            field=models.FileField(help_text='Selecione o arquivo PDF para assinar', upload_to='documents/original/%Y/%m/%d/', verbose_name='Documento Original'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='signature_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/signed/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='watermark_opacity',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.9)]),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='watermark_position',
            field=models.CharField(choices=[('center', 'Centro'), ('topleft', 'Superior Esquerdo'), ('topright', 'Superior Direito'), ('bottomleft', 'Inferior Esquerdo'), ('bottomright', 'Inferior Direito')], default='center', max_length=20),
        ),
    ]
