# Generated by Django 5.0.3 on 2025-04-16 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signer', '0002_alter_signeddocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signeddocument',
            name='watermark_position',
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/%d/', verbose_name='Imagem da Assinatura'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='signature_position',
            field=models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='left', max_length=10, verbose_name='Posição no Rodapé'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='signature_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto da Assinatura'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/signed/%Y/%m/%d/', verbose_name='Documento Assinado'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='watermark_opacity',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.9)], verbose_name="Transparência da Marca D'Água"),
        ),
    ]
