# Generated by Django 5.0.3 on 2025-05-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signer', '0003_remove_signeddocument_watermark_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocument',
            name='signature_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Posição X da Assinatura'),
        ),
        migrations.AddField(
            model_name='signeddocument',
            name='signature_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Posição Y da Assinatura'),
        ),
    ]
