# Generated by Django 5.0.3 on 2025-05-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signer', '0004_signeddocument_signature_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocument',
            name='signature_page',
            field=models.PositiveIntegerField(default=1, verbose_name='Página da Assinatura'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='signature_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='signature_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
