# Generated by Django 5.0.3 on 2025-06-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signer', '0005_signeddocument_signature_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocument',
            name='signature_mode',
            field=models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
    ]
